### ISSUE TITLE
facing error while running predixcan

### ISSUE THREAD

**Issue by ssalimi** [hakyimlab/Training#1]
Dear Dr. Hae Kyung Im, 

 For my project, I have tried to use predixcan software and faced an error. Neither me nor our bioinformatics expert found the solution. I am running the predixcan versus all genotype data(10,000,000 SNPs). Below is the copy of the error we have faced. I appreciate your guidance and help to be able to progress. Thank you in advance for your kind help. 
Best Regards,
Shabnam 

python ./PrediXcan.py --predict --dosages dosages --dosages_prefix chr --sample dosages/sample.txt -- weights Liver_LASSO.db --output_dir .
Below are first 3 lines of my sample.txt file:
10878 10878 0 0 0 0 -9
11655 11655 0 0 0 0 -9
12201 12201 0 0 0 0 -9
Below is the log file content:
2016-04-14 14:06:55.609509 Preloading weights...
2016-04-14 14:06:56.201847 Processing chr1.dosage.data.txt.gz
2016-04-14 14:24:10.396559 Processing chr10.dosage.data.txt.gz
2016-04-14 14:35:32.422774 Processing chr11.dosage.data.txt.gz
2016-04-14 14:46:11.936055 Processing chr12.dosage.data.txt.gz
2016-04-14 14:56:42.306676 Processing chr13.dosage.data.txt.gz
2016-04-14 15:04:40.451957 Processing chr14.dosage.data.txt.gz
2016-04-14 15:12:00.289541 Processing chr15.dosage.data.txt.gz
2016-04-14 15:18:19.583822 Processing chr16.dosage.data.txt.gz
2016-04-14 15:25:31.726997 Processing chr17.dosage.data.txt.gz
2016-04-14 15:31:46.137181 Processing chr18.dosage.data.txt.gz
2016-04-14 15:38:07.463976 Processing chr19.dosage.data.txt.gz
2016-04-14 15:43:57.293840 Processing chr2.dosage.data.txt.gz
2016-04-14 16:01:55.391602 Processing chr20.dosage.data.txt.gz
2016-04-14 16:07:00.779805 Processing chr21.dosage.data.txt.gz
2016-04-14 16:10:12.819881 Processing chr22.dosage.data.txt.gz
2016-04-14 16:13:29.788277 Processing chr3.dosage.data.txt.gz
2016-04-14 16:28:40.400313 Processing chr4.dosage.data.txt.gz
2016-04-14 16:44:31.586482 Processing chr5.dosage.data.txt.gz
2016-04-14 16:58:26.106604 Processing chr6.dosage.data.txt.gz
2016-04-14 17:12:43.945125 Processing chr7.dosage.data.txt.gz
2016-04-14 17:25:40.343552 Processing chr8.dosage.data.txt.gz
2016-04-14 17:38:02.067445 Processing chr9.dosage.data.txt.gz
Traceback (most recent call last):
File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 198, in 
main()
File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 181, in main
transcription_matrix.save(PRED_EXP_FILE)
File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 118, in save
outfile.write('\t'.join(next(sample_generator)) + '\t' + '\t'.join(map(str, self.D[:,col]))+'\n')
StopIteration

**Comment by ScottPDickinson** [comment]
Hi there,

Can you try specifying the --sample option as sample.txt instead of dosages/sample.txt?  The code already expects the sample file to be in the dosages directory.

**Comment by ssalimi** [comment]
Hi Scott,
We tried again considering your guidance but we faced the same problem, here it is what we got also our shell script. Looking forward to your advice. Thanks in advance. 

Here is the log file information from our recent run of PrediXcan.
 
Running on: node08. Starting: Tue Apr 19 10:43:42 EDT 2016
2016-04-19 10:43:42.850088 Preloading weights...
2016-04-19 10:43:43.540080 Processing chr1.dosage.data.txt.gz
2016-04-19 11:00:36.032037 Processing chr10.dosage.data.txt.gz
2016-04-19 11:11:41.297736 Processing chr11.dosage.data.txt.gz
2016-04-19 11:22:23.388229 Processing chr12.dosage.data.txt.gz
2016-04-19 11:32:55.254295 Processing chr13.dosage.data.txt.gz
2016-04-19 11:40:54.907850 Processing chr14.dosage.data.txt.gz
2016-04-19 11:48:16.862574 Processing chr15.dosage.data.txt.gz
2016-04-19 11:54:36.248002 Processing chr16.dosage.data.txt.gz
2016-04-19 12:01:49.090115 Processing chr17.dosage.data.txt.gz
2016-04-19 12:08:03.133216 Processing chr18.dosage.data.txt.gz
2016-04-19 12:14:24.003803 Processing chr19.dosage.data.txt.gz
2016-04-19 12:20:14.624484 Processing chr2.dosage.data.txt.gz
2016-04-19 12:38:14.322068 Processing chr20.dosage.data.txt.gz
2016-04-19 12:43:20.519245 Processing chr21.dosage.data.txt.gz
2016-04-19 12:46:30.723598 Processing chr22.dosage.data.txt.gz
2016-04-19 12:49:48.840590 Processing chr3.dosage.data.txt.gz
2016-04-19 13:05:05.002547 Processing chr4.dosage.data.txt.gz
2016-04-19 13:21:01.400857 Processing chr5.dosage.data.txt.gz
2016-04-19 13:34:56.756295 Processing chr6.dosage.data.txt.gz
2016-04-19 13:49:19.017410 Processing chr7.dosage.data.txt.gz
2016-04-19 14:02:18.567125 Processing chr8.dosage.data.txt.gz
2016-04-19 14:14:19.288260 Processing chr9.dosage.data.txt.gz
Traceback (most recent call last):
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 198, in <module>
    main()
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 181, in main
    transcription_matrix.save(PRED_EXP_FILE)
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 118, in save
    outfile.write('\t'.join(next(sample_generator)) + '\t' + '\t'.join(map(str, self.D[:,col]))+'\n')
StopIteration
Finished on: Tue Apr 19 14:24:28 EDT 2016

==== Shell Script
 
python=/data/ssalimi/packages/anaconda2/bin/python
script=/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py
dosages=/data/ssalimi/angpredix/dosages
dosagePrefix=chr
samplesFile=sample.txt
weightsDB=/data/ssalimi/angpredix/predictionModels/Liver_LASSO.db
outputDir=/data/ssalimi/angpredix
 
$python $script --predict --dosages $dosages --dosages_prefix $dosagePrefix --samples $samplesFile --weights $weightsDB --output_dir $outputDir
Best,
Shabnam

**Comment by ScottPDickinson** [comment]
Hmm.  The StopIteration error happens when there are no lines left to read in the samples file, but the code is asking for more.  Did the script at least start writing a predicted expression file in your output directory?  Can you double check to make sure that the number of rows in the sample file agrees with the number of columns for individuals in the dosage files?

**Comment by tushardave26** [comment]
Hello Scott,

Thanks for your help. You were right. Our dosage file had issues. We have fixed them and we are able to run the first step of our analysis (i.e. Predicting the scores). As a second step, we would like to run association analysis using PrediXcan. Unfortunately, we are facing some weird error. For your reference I have posted my bash script along with the error message:

SHELL SCRIPT ===
python=/data/ssalimi/packages/anaconda2/bin/python
script=/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py
phenoFile=/data/ssalimi/angpredix/phenotypes/phenotypeforpred.txt
predictedExpressionFile=/data/ssalimi/angpredix/predicted_expression.txt
filterFile=/data/ssalimi/angpredix/phenotypes/filter.txt
phenotype=pheno
outputDir=/data/ssalimi/angpredix

$python $script --assoc --pheno $phenoFile --pheno_name $phenotype --pred_exp $predictedExpressionFile --output_dir $outputDir --filter $filterFile 1 --linear

ERROR ===
Traceback (most recent call last):
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 198, in <module>
    main()
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 194, in main
    "OUT", ASSOC_FILE])
  File "/data/ssalimi/packages/anaconda2/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/data/ssalimi/packages/anaconda2/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/data/ssalimi/packages/anaconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

The error is weird because we have hard coded every file and directory path in my shell script. I believe, the script should find all the required file. Can you please help us to figure out the issue?

I hope my explanation is clear enough.

Thanks for your help.

Best,
Tushar

**Comment by ScottPDickinson** [comment]
Hi Tushar,

Glad I could help with the first issue.  If your dosage file was having issues, double check to make sure that the order of the sample.txt rows is the exact same as the columns in the dosage files.  Otherwise it won't match the individuals correctly and the analysis will be invalid.

Regarding the second issue, I'm not totally sure because I can't see your file structure, but I would first suggest using relative path names instead of absolute.  Is your data/ directory really in your root directory?  Depending on the file structure, and where you are calling the shell script from, it might be as simple as adding a '.' to the beginning of every file name.

**Comment by tushardave26** [comment]
Thanks Scott for your reply. Can you please help me to figure out which file the script is not able to find out? Because the error doesn't tell that explicitly. Thanks.

I am still unclear why the script gave out this error because every path is hard coded. I believe, the script should use them directly, no matter  from where I am invoking the script. Also, I am using SGE for submitting the job. In my script, I am using -wd qsub option to set the current working directory (i.e. /data/ssalimi/angpredix).

Thanks again for all your help.

**Comment by ScottPDickinson** [comment]
I see the issue now.  The file it isn't finding is PrediXcanAssociation.R, because the code is assuming that PrediXcan.py and PrediXcanAssociation.R are in the current working directory.

Adding one line might do the trick:
cd /data/ssalimi/data/ssalimi/packages/PrediXcan/Software/
$python $script --assoc --pheno $phenoFile --pheno_name $phenotype --pred_exp $predictedExpressionFile --output_dir $outputDir --filter $filterFile 1 --linear

If this doesn't work, let me know.

**Comment by tushardave26** [comment]
That's what I thought too. I am about to change the PrediXcan.py script line 184. That line has "./PrediXcanAssociation.R". Is there any way that you can fix this? Also, is there any way we can specify our output file name for both prediction scores and association?

Thanks for your help.

**Comment by ScottPDickinson** [comment]
There is no way to specify the output file names currently, but you are the second person to have asked in a short amount of time, and that's a feature we can add soon.

**Comment by tushardave26** [comment]
Thanks, Scott. One more question about R script. I can see PrediXcanAssociation.R has shebang line "#!/usr/env/bin Rscript". On our system, we don't have R installed on that location. Do you think I should change that line to reflect the correct location? We have installed R at /data/ssalimi/packages/R-3.2.3/bin/R. Till what should I add?

Thanks.

**Comment by ScottPDickinson** [comment]
Hi Tushar, sorry about the delay in response.  Can you double check the shebang line?  I have 
`#!/usr/bin/env Rscript`.

This line is supposed to help portability, but if it doesn't work, you'll have to adapt it.  I'd suggest typing

>which Rscript

into the command line to figure out what to replace it with.

**Comment by ssalimi** [comment]
Hello Scott,
Thanks for all your guidance. So far we could run the analysis, but a main question left for me. I want to evaluate the association between the SNPs of interest and gene expression levels from different genes to find out which genes' expressions are affected by SNP's dosage. In this case gene expression would be phenotype(outcome), right? If so, how we manage that? Thanks again for your guidance and walking us through the predixcan. 
Best,
Shabnam

**Comment by hakyim** [comment]
Hi Shabnam,

For that you should check the GTEx portal for eQTL information.

Haky

**Comment by ssalimi** [comment]
Hi Haky,
The results I get by predixcan are more interesting. 
What about if i run an ANOVA for gene expression scores from predixcan and the SNP of interest instead of using GTEx?
Thanks,
Shabnam

**Comment by hakyim** [comment]
I am not sure what you mean by that. What is the question you want to
answer?

Haky

**Comment by tushardave26** [comment]
Hello Scott,

Recently, I faced another error while trying to predicting the scores. Below is my script and error info:

**Script**

python=/data/ssalimi/packages/anaconda2/bin/python
script=/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py
dosages=/data/ssalimi/angpredix/dosages
dosagePrefix=chr
samplesFile=sample.txt
weightsDB=/data/ssalimi/angpredix/predictionModels/Heart_Left_Ventricle_LASSO.db
outputDir=/data/ssalimi/angpredix

$python $script --predict --dosages $dosages --dosages_prefix $dosagePrefix --samples $samplesFile --weights $weightsDB --output_dir $outputDir

**Error**

Running on: head. Starting: Thu Jun 2 15:00:54 EDT 2016
2016-06-02 15:00:59.895655 Preloading weights...
2016-06-02 15:01:00.556252 Processing chr1.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.556867 Processing chr10.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.557269 Processing chr11.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.557666 Processing chr12.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.558051 Processing chr13.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.558441 Processing chr14.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.558824 Processing chr15.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.559202 Processing chr16.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.560136 Processing chr17.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.560817 Processing chr18.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.561268 Processing chr19.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.561691 Processing chr2.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.562109 Processing chr20.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.562547 Processing chr21.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.562971 Processing chr22.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.563389 Processing chr3.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.563809 Processing chr4.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.565579 Processing chr5.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.566040 Processing chr6.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.566477 Processing chr7.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.566899 Processing chr8.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
2016-06-02 15:01:00.599756 Processing chr9.GWAS.only.pval.lt9E-7.dosage.data.txt.gz
Traceback (most recent call last):
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 198, in <module>
    main()
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 181, in main
    transcription_matrix.save(PRED_EXP_FILE)
  File "/data/ssalimi/packages/PrediXcan/Software/PrediXcan.py", line 116, in save
    outfile.write('FID\t' + 'IID\t' + '\t'.join(self.gene_list) + '\n') # Nb. this lists the names of rows, not of columns
AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'
Finished on: Thu Jun 2 15:01:00 EDT 2016

Let me tell you something here. We choose the SNPs that have p-value < 9E-7. So we have a smaller number of SNPs and they all are in two chromosomes (e.g. Chr -1 and Chr - 2). Your program is looking for chr-1 to chr-22 dosage files. So we keep other files there with no content in them. Do you think this might cause the error? 

Can you please help us to resolve the issue?

I hope I am clear enough in explaining the issue.

Thanks.

**Comment by ruoxichen5** [comment]
Hi tushardave26,

Were you able to solve this AttributeError issue? I have the same problem.

Thanks

**Comment by ruoxichen5** [comment]
[75bfbedbedbb22a1ffa6a17c57b9f770.tar.gz](https://github.com/hakyimlab/Training/files/429022/75bfbedbedbb22a1ffa6a17c57b9f770.tar.gz)

**Comment by wangfan860** [comment]
@ScottPDickinson Hi, Scott, I'm getting the same error "TranscriptionMatrix instance has no attribute 'gene_list'". Can you please tell me how to solve the problem?

@tushardave26 Hello, I also got the AttributeError when running predixcan, have you got the answer?

Thank you all!

**Comment by ScottPDickinson** [comment]
Hey Fan,
Can you double check two things? First, make sure the path to you genotype dosages is correct. Then, see if the rsids that are in your files are used in the prediction database. The error you're getting might happen if none of your snps are in the database. Keep us posted.

**Comment by wangfan860** [comment]
Hello Scott, thank you so much for the response. I can run my scripts without any error this time. However, I only get 4400 genes in the result file. I think I’m having a problem that the dbsnp build in my dataset (only SNPs matching existing 1000 genome genotype were kept, followed by pre-phasing with SHAPEIT and genotype imputation with IMPUTE2) is not dbsnp142 and i think it should be older than 142. I'm wondering if you have any tools or tricks which could upgrade the dbsnp build based on chr, position, alleles? if not do you have any suggestions? Thank you very much!!!

**Comment by wangfan860** [comment]
@ScottPDickinson Hi, Scott, another problem I have is the ENSG ID. I found decimal points in the ENSG id, eg. ENSG00000002822.11 and ENSG00000003509.11. Are they supposed to be like this? Thanks again!

**Comment by wangfan860** [comment]
Thank you so much for your help! @ScottPDickinson

**Comment by duttaind** [comment]
@wangfan860 or ScottPDickinson,,

Hello,
Could you please share how you solved AttributeError: TranscriptionMatrix instance has no attribute 'gene_list' error. I read all github posts as well as checked file formats. I am not able to execute either PredixcanExample data or our own data for step1 of predixcan to get predicted expression. Both execution showing same error mentioned above. Thanks in advance.

I have posted errors and more details at Predixcan google user group too.

**Comment by hakyim** [comment]
I just noticed this question from 3.5 years ago. Hopefully, it was resolved. If you have further questions please email predixcanmetaxcan@googlegroups.com
